### ISSUE TITLE
When deprecated UploadMediaItemRequest.fileName is omitted, Google responds with HTTP 500

### ISSUE THREAD

**Issue by ylexus** [google/java-photoslibrary#42] opened 2021-01-23 22:35 UTC
uploadMediaItem fails if the deprecated UploadMediaItemRequest.fileName is omitted. Workaround is to supply some value there, and then also specify the file name in NewMediaItem too - that last one is then used, and UploadMediaItemRequest.fileName is ignored.

Here's the DEBUG level request and response:
```
2021-01-23T22:27:10,742 DEBUG [Gax-2] o.a.h.i.c.Wire http-outgoing-0 >> "POST /v1/uploads HTTP/1.1[\r][\n]"
2021-01-23T22:27:10,743 DEBUG [Gax-2] o.a.h.i.c.Wire http-outgoing-0 >> "Authorization: Bearer <censored>[\r][\n]"
2021-01-23T22:27:10,743 DEBUG [Gax-2] o.a.h.i.c.Wire http-outgoing-0 >> "X-Goog-Upload-Protocol: resumable[\r][\n]"
2021-01-23T22:27:10,743 DEBUG [Gax-2] o.a.h.i.c.Wire http-outgoing-0 >> "X-Goog-Upload-Command: start[\r][\n]"
2021-01-23T22:27:10,743 DEBUG [Gax-2] o.a.h.i.c.Wire http-outgoing-0 >> "X-Goog-Upload-Raw-Size: 29416[\r][\n]"
2021-01-23T22:27:10,743 DEBUG [Gax-2] o.a.h.i.c.Wire http-outgoing-0 >> "Content-Length: 0[\r][\n]"
2021-01-23T22:27:10,743 DEBUG [Gax-2] o.a.h.i.c.Wire http-outgoing-0 >> "Host: photoslibrary.googleapis.com[\r][\n]"
2021-01-23T22:27:10,743 DEBUG [Gax-2] o.a.h.i.c.Wire http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
2021-01-23T22:27:10,743 DEBUG [Gax-2] o.a.h.i.c.Wire http-outgoing-0 >> "User-Agent: Apache-HttpClient/4.5.12 (Java/14.0.2)[\r][\n]"
2021-01-23T22:27:10,743 DEBUG [Gax-2] o.a.h.i.c.Wire http-outgoing-0 >> "Accept-Encoding: gzip,deflate[\r][\n]"
2021-01-23T22:27:10,743 DEBUG [Gax-2] o.a.h.i.c.Wire http-outgoing-0 >> "[\r][\n]"
2021-01-23T22:27:10,796 DEBUG [Gax-2] o.a.h.i.c.Wire http-outgoing-0 << "HTTP/1.1 500 Internal Server Error[\r][\n]"
2021-01-23T22:27:10,797 DEBUG [Gax-2] o.a.h.i.c.Wire http-outgoing-0 << "X-GUploader-UploadID: <censored>[\r][\n]"
2021-01-23T22:27:10,797 DEBUG [Gax-2] o.a.h.i.c.Wire http-outgoing-0 << "X-Goog-Upload-Status: final[\r][\n]"
2021-01-23T22:27:10,797 DEBUG [Gax-2] o.a.h.i.c.Wire http-outgoing-0 << "Content-Length: 60[\r][\n]"
2021-01-23T22:27:10,797 DEBUG [Gax-2] o.a.h.i.c.Wire http-outgoing-0 << "Date: Sat, 23 Jan 2021 22:27:11 GMT[\r][\n]"
2021-01-23T22:27:10,797 DEBUG [Gax-2] o.a.h.i.c.Wire http-outgoing-0 << "Server: UploadServer[\r][\n]"
2021-01-23T22:27:10,797 DEBUG [Gax-2] o.a.h.i.c.Wire http-outgoing-0 << "Content-Type: text/html; charset=UTF-8[\r][\n]"
2021-01-23T22:27:10,797 DEBUG [Gax-2] o.a.h.i.c.Wire http-outgoing-0 << "Alt-Svc: h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"[\r][\n]"
2021-01-23T22:27:10,797 DEBUG [Gax-2] o.a.h.i.c.Wire http-outgoing-0 << "[\r][\n]"
2021-01-23T22:27:10,797 DEBUG [Gax-2] o.a.h.i.c.Wire http-outgoing-0 << "{[\n]"
2021-01-23T22:27:10,798 DEBUG [Gax-2] o.a.h.i.c.Wire http-outgoing-0 << "  "code": 13,[\n]"
2021-01-23T22:27:10,798 DEBUG [Gax-2] o.a.h.i.c.Wire http-outgoing-0 << "  "message": "Internal error encountered."[\n]"
2021-01-23T22:27:10,798 DEBUG [Gax-2] o.a.h.i.c.Wire http-outgoing-0 << "}"
2021-01-23T22:27:10,800 DEBUG [Gax-2] o.a.h.i.c.LoggingManagedHttpClientConnection http-outgoing-0 << HTTP/1.1 500 Internal Server Error
2021-01-23T22:27:10,800 DEBUG [Gax-2] o.a.h.i.c.LoggingManagedHttpClientConnection http-outgoing-0 << X-GUploader-UploadID: ABg5-UyfTegj2uYUwTskwNDFqj_-Mh8BV2OC7mUEZ0xjGUGdUaDB1fLw3BFv2WvxAszzsWjus70BG5D0SJctaWkyOdk
2021-01-23T22:27:10,800 DEBUG [Gax-2] o.a.h.i.c.LoggingManagedHttpClientConnection http-outgoing-0 << X-Goog-Upload-Status: final
2021-01-23T22:27:10,800 DEBUG [Gax-2] o.a.h.i.c.LoggingManagedHttpClientConnection http-outgoing-0 << Content-Length: 60
2021-01-23T22:27:10,800 DEBUG [Gax-2] o.a.h.i.c.LoggingManagedHttpClientConnection http-outgoing-0 << Date: Sat, 23 Jan 2021 22:27:11 GMT
2021-01-23T22:27:10,800 DEBUG [Gax-2] o.a.h.i.c.LoggingManagedHttpClientConnection http-outgoing-0 << Server: UploadServer
2021-01-23T22:27:10,800 DEBUG [Gax-2] o.a.h.i.c.LoggingManagedHttpClientConnection http-outgoing-0 << Content-Type: text/html; charset=UTF-8
2021-01-23T22:27:10,800 DEBUG [Gax-2] o.a.h.i.c.LoggingManagedHttpClientConnection http-outgoing-0 << Alt-Svc: h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"

```

**Comment by jfschmakeit** [comment] 2021-02-10 03:47
I haven't been able to reproduce this. Calling only `setFileName` on a `NewMediaItem` and omitting the file name from the `UploadMediaItemRequest` seems to work as expected. (Per the [documentation](https://developers.google.com/photos/library/guides/upload-media#uploading-bytes) and the sample app.)

Could you post a code snippets that shows the calls to the API and the construction of the relevant request objects? 

Thanks!

**Comment by ylexus** [comment] 2021-02-10 19:54
The code is in https://github.com/ylexus/jiotty/blob/master/jiotty-connector-google/jiotty-connector-google-photos/src/main/java/net/yudichev/jiotty/connector/google/photos/GooglePhotosClientImpl.java, methods `uploadMediaData` and `createMediaItems`. Particularly, line 62.
If you need a reproducible scenario, then 
1. ensure JAVA_HOME points to jdk 14. 
1. clone https://github.com/ylexus/jiotty-photos-uploader
1. change `jiotty-photos-uploader/buld.gradle`, replace version in `ext.netYudichevJiottyVersion` to the one in `jiotty/pom.xml`
1. in jiotty-photos-uploader, execute `./gradlew run`
1. when the app starts, login to the google account, select some folder with photos and click start
1. it will error, the error will be in `log ~/.jiottyphotosuploader/logs/main.log`

**Comment by ylexus** [comment] 2021-02-10 20:04
Just tried and it' still perfectly reproducible.

**Comment by jfschmakeit** [comment] 2021-02-15 02:47
The issue is that you are not supplying a mime type in your `UploadMediaItemRequest`. You need to call `.setMimeType(..)` with the mime type of the file you are uploading. When this property is set, you do not need to include the deprecated filename property for the upload call to work. 

(I have confirmed that I'm getting the same error when making an upload call without setting the mime type.)

I'm closing this issue for now, but please reopen if you are still seeing this even after setting the mime type on your upload request.

**Closed by jfschmakeit** 2021-02-15 02:47 UTC
Labels: question

**Comment by ylexus** [comment] 2021-02-20 16:09
@jfschmakeit according to https://developers.google.com/photos/library/guides/upload-media#uploading-bytes, "X-Goog-Upload-Content-Type" is recommended, but not mandatory.

Apparently, in practice either "X-Goog-Upload-Content-Type" or "X-Goog-Upload-File-Name" is required. Sounds like an undocumented feature, or is, indeed, a bug on the Google serve side. Anything we can do to let them know?
